/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package neuralnetjava;

import neuralnetjava.network.NeuralNet;
import neuralnetjava.network.NeuralNetMatrixToolkit;
import neuralnetjava.network.mnistReader.*;
import org.javatuples.Pair;
import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.RealMatrix;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public static void main(String[] args) throws Exception {
        MnistMatrixData[] mnistMatrix_training = MnistDataReader.readData("app/src/main/java/neuralnetjava/network/mnistReader/data/train-images.idx3-ubyte", "app/src/main/java/neuralnetjava/network/mnistReader/data/train-labels.idx1-ubyte");
        ArrayList<Pair<RealMatrix, Integer>> training_input = new ArrayList<>();
        for (MnistMatrixData mx : mnistMatrix_training) {
            mx.convertInputToRealMatrix();
            training_input.add(mx.getInput());
        }

        MnistMatrixData[] mnistMatrix_test = MnistDataReader.readData("app/src/main/java/neuralnetjava/network/mnistReader/data/t10k-images.idx3-ubyte", "app/src/main/java/neuralnetjava/network/mnistReader/data/t10k-labels.idx1-ubyte");
        ArrayList<Pair<RealMatrix, Integer>> test_input = new ArrayList<>();
        for (MnistMatrixData mx : mnistMatrix_test) {
            mx.convertInputToRealMatrix();
            test_input.add(mx.getInput());
        }

        int[] netStructure = {784, 30, 10};
        NeuralNet net = new NeuralNet(netStructure);
        net.SGD(training_input, 30, 10, 3.5, test_input);
    }
}